name: Install dependencies

description: Install dependencies

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      name: Install Bun
      with:
        version: "1.2.22"

    - name: Cache Bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Build
      shell: bash
      run: bun run build
