// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type {
  UserContextError,
  UserContextResponse,
  AppContextError,
  AppContextResponse,
  UpdateUserSettingsData,
  UpdateUserSettingsError,
  UpdateUserSettingsResponse,
  AcknowledgeWelcomeData,
  AcknowledgeWelcomeError,
  AcknowledgeWelcomeResponse,
  SystemLoadError,
  SystemLoadResponse,
  DownloadLocalCertificateError,
  DownloadLocalCertificateResponse,
  GetTranslationData,
  GetTranslationError,
  GetTranslationResponse,
  LoginData,
  LoginError,
  LoginResponse,
  VerifyTotpData,
  VerifyTotpError,
  VerifyTotpResponse,
  RegisterData,
  RegisterError,
  RegisterResponse,
  LogoutError,
  LogoutResponse,
  ChangeUsernameData,
  ChangeUsernameError,
  ChangeUsernameResponse,
  ChangePasswordData,
  ChangePasswordError,
  ChangePasswordResponse,
  GetTotpUriData,
  GetTotpUriError,
  GetTotpUriResponse,
  SetupTotpData,
  SetupTotpError,
  SetupTotpResponse,
  DisableTotpData,
  DisableTotpError,
  DisableTotpResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  CancelResetPasswordError,
  CancelResetPasswordResponse,
  CheckResetPasswordRequestError,
  CheckResetPasswordRequestResponse,
  GetInstalledAppsError,
  GetInstalledAppsResponse,
  GetGuestAppsError,
  GetGuestAppsResponse,
  SearchAppsData,
  SearchAppsError,
  SearchAppsResponse,
  GetAppDetailsData,
  GetAppDetailsError,
  GetAppDetailsResponse,
  GetImageData,
  GetImageError,
  GetImageResponse,
  PullError,
  PullResponse,
  InstallAppData,
  InstallAppError,
  InstallAppResponse,
  StartAppData,
  StartAppError,
  StartAppResponse,
  StopAppData,
  StopAppError,
  StopAppResponse,
  RestartAppData,
  RestartAppError,
  RestartAppResponse,
  UninstallAppData,
  UninstallAppError,
  UninstallAppResponse,
  ResetAppData,
  ResetAppError,
  ResetAppResponse,
  UpdateAppData,
  UpdateAppError,
  UpdateAppResponse,
  UpdateAllAppsError,
  UpdateAllAppsResponse,
  UpdateAppConfigData,
  UpdateAppConfigError,
  UpdateAppConfigResponse,
  BackupAppData,
  BackupAppError,
  BackupAppResponse,
  RestoreAppBackupData,
  RestoreAppBackupError,
  RestoreAppBackupResponse,
  GetAppBackupsData,
  GetAppBackupsError,
  GetAppBackupsResponse,
  DeleteAppBackupData,
  DeleteAppBackupError,
  DeleteAppBackupResponse,
  GetLinksError,
  GetLinksResponse,
  CreateLinkData,
  CreateLinkError,
  CreateLinkResponse,
  EditLinkData,
  EditLinkError,
  EditLinkResponse,
  DeleteLinkData,
  DeleteLinkError,
  DeleteLinkResponse,
  CheckError,
  CheckResponse,
} from './types.gen';

export const client = createClient(createConfig());

export const userContext = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<UserContextResponse, UserContextError, ThrowOnError>({
    ...options,
    url: '/api/user-context',
  });
};

export const appContext = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<AppContextResponse, AppContextError, ThrowOnError>({
    ...options,
    url: '/api/app-context',
  });
};

export const updateUserSettings = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateUserSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).patch<UpdateUserSettingsResponse, UpdateUserSettingsError, ThrowOnError>({
    ...options,
    url: '/api/user-settings',
  });
};

export const acknowledgeWelcome = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AcknowledgeWelcomeData, ThrowOnError>) => {
  return (options?.client ?? client).patch<AcknowledgeWelcomeResponse, AcknowledgeWelcomeError, ThrowOnError>({
    ...options,
    url: '/api/acknowledge-welcome',
  });
};

export const systemLoad = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<SystemLoadResponse, SystemLoadError, ThrowOnError>({
    ...options,
    url: '/api/system/load',
  });
};

export const downloadLocalCertificate = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<DownloadLocalCertificateResponse, DownloadLocalCertificateError, ThrowOnError>({
    ...options,
    url: '/api/system/certificate',
  });
};

export const getTranslation = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTranslationData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetTranslationResponse, GetTranslationError, ThrowOnError>({
    ...options,
    url: '/api/i18n/locales/{ns}/{lng}.json',
  });
};

export const login = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginData, ThrowOnError>) => {
  return (options?.client ?? client).post<LoginResponse, LoginError, ThrowOnError>({
    ...options,
    url: '/api/auth/login',
  });
};

export const verifyTotp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<VerifyTotpData, ThrowOnError>) => {
  return (options?.client ?? client).post<VerifyTotpResponse, VerifyTotpError, ThrowOnError>({
    ...options,
    url: '/api/auth/verify-totp',
  });
};

export const register = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RegisterData, ThrowOnError>) => {
  return (options?.client ?? client).post<RegisterResponse, RegisterError, ThrowOnError>({
    ...options,
    url: '/api/auth/register',
  });
};

export const logout = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).post<LogoutResponse, LogoutError, ThrowOnError>({
    ...options,
    url: '/api/auth/logout',
  });
};

export const changeUsername = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ChangeUsernameData, ThrowOnError>) => {
  return (options?.client ?? client).patch<ChangeUsernameResponse, ChangeUsernameError, ThrowOnError>({
    ...options,
    url: '/api/auth/username',
  });
};

export const changePassword = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ChangePasswordData, ThrowOnError>) => {
  return (options?.client ?? client).patch<ChangePasswordResponse, ChangePasswordError, ThrowOnError>({
    ...options,
    url: '/api/auth/password',
  });
};

export const getTotpUri = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTotpUriData, ThrowOnError>) => {
  return (options?.client ?? client).patch<GetTotpUriResponse, GetTotpUriError, ThrowOnError>({
    ...options,
    url: '/api/auth/totp/get-uri',
  });
};

export const setupTotp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SetupTotpData, ThrowOnError>) => {
  return (options?.client ?? client).patch<SetupTotpResponse, SetupTotpError, ThrowOnError>({
    ...options,
    url: '/api/auth/totp/setup',
  });
};

export const disableTotp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DisableTotpData, ThrowOnError>) => {
  return (options?.client ?? client).patch<DisableTotpResponse, DisableTotpError, ThrowOnError>({
    ...options,
    url: '/api/auth/totp/disable',
  });
};

export const resetPassword = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ResetPasswordData, ThrowOnError>) => {
  return (options?.client ?? client).post<ResetPasswordResponse, ResetPasswordError, ThrowOnError>({
    ...options,
    url: '/api/auth/reset-password',
  });
};

export const cancelResetPassword = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).delete<CancelResetPasswordResponse, CancelResetPasswordError, ThrowOnError>({
    ...options,
    url: '/api/auth/reset-password',
  });
};

export const checkResetPasswordRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<CheckResetPasswordRequestResponse, CheckResetPasswordRequestError, ThrowOnError>({
    ...options,
    url: '/api/auth/reset-password',
  });
};

export const getInstalledApps = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetInstalledAppsResponse, GetInstalledAppsError, ThrowOnError>({
    ...options,
    url: '/api/apps/installed',
  });
};

export const getGuestApps = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetGuestAppsResponse, GetGuestAppsError, ThrowOnError>({
    ...options,
    url: '/api/apps/guest',
  });
};

export const searchApps = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<SearchAppsData, ThrowOnError>) => {
  return (options?.client ?? client).get<SearchAppsResponse, SearchAppsError, ThrowOnError>({
    ...options,
    url: '/api/apps/search',
  });
};

export const getAppDetails = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetAppDetailsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetAppDetailsResponse, GetAppDetailsError, ThrowOnError>({
    ...options,
    url: '/api/apps/{id}',
  });
};

export const getImage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetImageData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetImageResponse, GetImageError, ThrowOnError>({
    ...options,
    url: '/api/apps/{id}/image',
  });
};

export const pull = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).post<PullResponse, PullError, ThrowOnError>({
    ...options,
    url: '/api/repos/pull',
  });
};

export const installApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<InstallAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<InstallAppResponse, InstallAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/install',
  });
};

export const startApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<StartAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<StartAppResponse, StartAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/start',
  });
};

export const stopApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<StopAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<StopAppResponse, StopAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/stop',
  });
};

export const restartApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RestartAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<RestartAppResponse, RestartAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/restart',
  });
};

export const uninstallApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UninstallAppData, ThrowOnError>) => {
  return (options?.client ?? client).delete<UninstallAppResponse, UninstallAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/uninstall',
  });
};

export const resetApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ResetAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<ResetAppResponse, ResetAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/reset',
  });
};

export const updateApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateAppData, ThrowOnError>) => {
  return (options?.client ?? client).patch<UpdateAppResponse, UpdateAppError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/update',
  });
};

export const updateAllApps = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).patch<UpdateAllAppsResponse, UpdateAllAppsError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/update-all',
  });
};

export const updateAppConfig = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateAppConfigData, ThrowOnError>) => {
  return (options?.client ?? client).patch<UpdateAppConfigResponse, UpdateAppConfigError, ThrowOnError>({
    ...options,
    url: '/api/app-lifecycle/{id}/update-config',
  });
};

export const backupApp = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<BackupAppData, ThrowOnError>) => {
  return (options?.client ?? client).post<BackupAppResponse, BackupAppError, ThrowOnError>({
    ...options,
    url: '/api/backups/{appid}/backup',
  });
};

export const restoreAppBackup = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RestoreAppBackupData, ThrowOnError>) => {
  return (options?.client ?? client).post<RestoreAppBackupResponse, RestoreAppBackupError, ThrowOnError>({
    ...options,
    url: '/api/backups/{appid}/restore',
  });
};

export const getAppBackups = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetAppBackupsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetAppBackupsResponse, GetAppBackupsError, ThrowOnError>({
    ...options,
    url: '/api/backups/{id}',
  });
};

export const deleteAppBackup = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteAppBackupData, ThrowOnError>) => {
  return (options?.client ?? client).delete<DeleteAppBackupResponse, DeleteAppBackupError, ThrowOnError>({
    ...options,
    url: '/api/backups/{appid}',
  });
};

export const getLinks = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetLinksResponse, GetLinksError, ThrowOnError>({
    ...options,
    url: '/api/links',
  });
};

export const createLink = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateLinkData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateLinkResponse, CreateLinkError, ThrowOnError>({
    ...options,
    url: '/api/links',
  });
};

export const editLink = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<EditLinkData, ThrowOnError>) => {
  return (options?.client ?? client).patch<EditLinkResponse, EditLinkError, ThrowOnError>({
    ...options,
    url: '/api/links/{id}',
  });
};

export const deleteLink = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteLinkData, ThrowOnError>) => {
  return (options?.client ?? client).delete<DeleteLinkResponse, DeleteLinkError, ThrowOnError>({
    ...options,
    url: '/api/links/{id}',
  });
};

export const check = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<CheckResponse, CheckError, ThrowOnError>({
    ...options,
    url: '/api/health',
  });
};
