// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UserContextDto = {
    allowAutoThemes: boolean;
    allowErrorMonitoring: boolean;
    isConfigured: boolean;
    isGuestDashboardEnabled: boolean;
    isLoggedIn: boolean;
    localDomain: string;
    sslPort: number;
    themeBase: string;
    themeColor: string;
    version: {
        body: string;
        current: string;
        latest: string;
        releases: Array<{
            body: string;
            version: string;
        }>;
    };
};

export type AppContextDto = {
    apps: Array<{
        available: boolean;
        categories: Array<'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities'>;
        created_at: number;
        deprecated: boolean;
        id: string;
        name: string;
        short_desc: string;
        supported_architectures: Array<'amd64' | 'arm64'>;
        urn: string;
    }>;
    updatesAvailable: number;
    user: {
        hasSeenWelcome: boolean;
        id: number;
        locale: string;
        operator: boolean;
        totpEnabled: boolean;
        username: string;
    };
    userSettings: {
        advancedSettings: boolean;
        allowAutoThemes: boolean;
        allowErrorMonitoring: boolean;
        appDataPath: string;
        appsRepoUrl: string;
        demoMode: boolean;
        dnsIp: string;
        domain: string;
        eventsTimeout: number;
        forwardAuthUrl: string;
        guestDashboard: boolean;
        internalIp: string;
        listenIp: string;
        localDomain: string;
        logLevel: 'debug' | 'error' | 'info' | 'warn';
        maxBackups: number;
        persistTraefikConfig: boolean;
        port: number;
        postgresPort: number;
        sslPort: number;
        timeZone: string;
        experimental_insecureCookie?: boolean;
        themeBase?: string;
        themeColor?: string;
    };
    version: {
        body: string;
        current: string;
        latest: string;
        releases: Array<{
            body: string;
            version: string;
        }>;
    };
};

export type UserSettingsBody = {
    advancedSettings?: boolean;
    allowAutoThemes?: boolean;
    allowErrorMonitoring?: boolean;
    appDataPath?: string;
    appsRepoUrl?: string;
    demoMode?: boolean;
    dnsIp?: string;
    domain?: string;
    eventsTimeout?: number | string;
    experimental_insecureCookie?: boolean;
    forwardAuthUrl?: string;
    guestDashboard?: boolean;
    internalIp?: string;
    listenIp?: string;
    localDomain?: string;
    logLevel?: 'debug' | 'error' | 'info' | 'warn';
    maxBackups?: number | string;
    persistTraefikConfig?: boolean;
    port?: number | string;
    postgresPort?: number | string;
    sslPort?: number | string;
    themeBase?: string;
    themeColor?: string;
    timeZone?: string;
};

export type AcknowledgeWelcomeBody = {
    allowErrorMonitoring: boolean;
};

export type LoadDto = {
    cpuLoad: number;
    diskSize: number;
    diskUsed: number;
    memoryTotal: number;
    percentUsed: number;
    percentUsedMemory: number;
};

export type LoginBody = {
    password: string;
    username: string;
};

export type LoginDto = {
    success: boolean;
    totpSessionId?: string;
};

export type VerifyTotpBody = {
    totpCode: string;
    totpSessionId: string;
};

export type RegisterBody = {
    password: string;
    username: string;
};

export type RegisterDto = {
    success: boolean;
};

export type ChangeUsernameBody = {
    newUsername: string;
    password: string;
};

export type ChangePasswordBody = {
    currentPassword: string;
    newPassword: string;
};

export type GetTotpUriBody = {
    password: string;
};

export type GetTotpUriDto = {
    key: string;
    uri: string;
};

export type SetupTotpBody = {
    code: string;
};

export type DisableTotpBody = {
    password: string;
};

export type ResetPasswordBody = {
    newPassword: string;
};

export type ResetPasswordDto = {
    email: string;
    success: boolean;
};

export type CheckResetPasswordRequestDto = {
    isRequestPending: boolean;
};

export type MyAppsDto = {
    installed: Array<{
        app: {
            domain: string | null;
            exposed: boolean;
            exposedLocal: boolean;
            id: number;
            ignoredVersion: number | null;
            isVisibleOnGuestDashboard: boolean;
            openPort: boolean;
            pendingRestart: boolean;
            port: number | null;
            status: 'backing_up' | 'installing' | 'missing' | 'resetting' | 'restarting' | 'restoring' | 'running' | 'starting' | 'stopped' | 'stopping' | 'uninstalling' | 'updating';
            version: number;
            config?: {
                [key: string]: unknown;
            };
            createdAt?: string;
            enableAuth?: boolean;
            localSubdomain?: string | null;
            updatedAt?: string;
        };
        info: {
            author: string;
            available: boolean;
            categories: Array<'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities'>;
            created_at: number;
            deprecated: boolean;
            description: string;
            dynamic_config: boolean;
            exposable: boolean;
            force_expose: boolean;
            force_pull: boolean;
            form_fields: Array<{
                env_variable: string;
                label: string;
                required: boolean;
                type: 'boolean' | 'email' | 'fqdn' | 'fqdnip' | 'ip' | 'number' | 'password' | 'random' | 'text' | 'url';
                default?: number | string | boolean;
                encoding?: 'base64' | 'hex';
                hint?: string;
                max?: number;
                min?: number;
                options?: Array<{
                    label: string;
                    value: string;
                }>;
                pattern_error?: string;
                placeholder?: string;
                regex?: string;
            }>;
            generate_vapid_keys: boolean;
            https: boolean;
            id: string;
            name: string;
            no_gui: boolean;
            short_desc: string;
            source: string;
            supported_architectures: Array<'amd64' | 'arm64'>;
            tipi_version: number;
            updated_at: number;
            urn: string;
            version: string;
            gid?: number;
            min_tipi_version?: string;
            port?: number;
            uid?: number;
            url_suffix?: string;
            website?: string;
        };
        metadata: {
            latestVersion: number;
            localSubdomain: string;
            composeSchemaVersion?: number;
            hasCustomConfig?: boolean;
            latestDockerVersion?: string;
            minTipiVersion?: string | null;
        };
    }>;
};

export type GuestAppsDto = {
    installed: Array<{
        app: {
            domain: string | null;
            exposed: boolean;
            exposedLocal: boolean;
            id: number;
            ignoredVersion: number | null;
            isVisibleOnGuestDashboard: boolean;
            openPort: boolean;
            pendingRestart: boolean;
            port: number | null;
            status: 'backing_up' | 'installing' | 'missing' | 'resetting' | 'restarting' | 'restoring' | 'running' | 'starting' | 'stopped' | 'stopping' | 'uninstalling' | 'updating';
            version: number;
            config?: {
                [key: string]: unknown;
            };
            createdAt?: string;
            enableAuth?: boolean;
            localSubdomain?: string | null;
            updatedAt?: string;
        };
        info: {
            author: string;
            available: boolean;
            categories: Array<'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities'>;
            created_at: number;
            deprecated: boolean;
            description: string;
            dynamic_config: boolean;
            exposable: boolean;
            force_expose: boolean;
            force_pull: boolean;
            form_fields: Array<{
                env_variable: string;
                label: string;
                required: boolean;
                type: 'boolean' | 'email' | 'fqdn' | 'fqdnip' | 'ip' | 'number' | 'password' | 'random' | 'text' | 'url';
                default?: number | string | boolean;
                encoding?: 'base64' | 'hex';
                hint?: string;
                max?: number;
                min?: number;
                options?: Array<{
                    label: string;
                    value: string;
                }>;
                pattern_error?: string;
                placeholder?: string;
                regex?: string;
            }>;
            generate_vapid_keys: boolean;
            https: boolean;
            id: string;
            name: string;
            no_gui: boolean;
            short_desc: string;
            source: string;
            supported_architectures: Array<'amd64' | 'arm64'>;
            tipi_version: number;
            updated_at: number;
            urn: string;
            version: string;
            gid?: number;
            min_tipi_version?: string;
            port?: number;
            uid?: number;
            url_suffix?: string;
            website?: string;
        };
        metadata: {
            latestVersion: number;
            localSubdomain: string;
            composeSchemaVersion?: number;
            hasCustomConfig?: boolean;
            latestDockerVersion?: string;
            minTipiVersion?: string | null;
        };
    }>;
};

export type GetRandomPortDto = {
    port: number;
};

export type GetAppDto = {
    info: {
        author: string;
        available: boolean;
        categories: Array<'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities'>;
        created_at: number;
        deprecated: boolean;
        description: string;
        dynamic_config: boolean;
        exposable: boolean;
        force_expose: boolean;
        force_pull: boolean;
        form_fields: Array<{
            env_variable: string;
            label: string;
            required: boolean;
            type: 'boolean' | 'email' | 'fqdn' | 'fqdnip' | 'ip' | 'number' | 'password' | 'random' | 'text' | 'url';
            default?: number | string | boolean;
            encoding?: 'base64' | 'hex';
            hint?: string;
            max?: number;
            min?: number;
            options?: Array<{
                label: string;
                value: string;
            }>;
            pattern_error?: string;
            placeholder?: string;
            regex?: string;
        }>;
        generate_vapid_keys: boolean;
        https: boolean;
        id: string;
        name: string;
        no_gui: boolean;
        short_desc: string;
        source: string;
        supported_architectures: Array<'amd64' | 'arm64'>;
        tipi_version: number;
        updated_at: number;
        urn: string;
        version: string;
        gid?: number;
        min_tipi_version?: string;
        port?: number;
        uid?: number;
        url_suffix?: string;
        website?: string;
    };
    metadata: {
        latestVersion: number;
        localSubdomain: string;
        composeSchemaVersion?: number;
        hasCustomConfig?: boolean;
        latestDockerVersion?: string;
        minTipiVersion?: string | null;
    };
    app?: {
        domain: string | null;
        exposed: boolean;
        exposedLocal: boolean;
        id: number;
        ignoredVersion: number | null;
        isVisibleOnGuestDashboard: boolean;
        openPort: boolean;
        pendingRestart: boolean;
        port: number | null;
        status: 'backing_up' | 'installing' | 'missing' | 'resetting' | 'restarting' | 'restoring' | 'running' | 'starting' | 'stopped' | 'stopping' | 'uninstalling' | 'updating';
        version: number;
        config?: {
            [key: string]: unknown;
        };
        createdAt?: string;
        enableAuth?: boolean;
        localSubdomain?: string | null;
        updatedAt?: string;
    } | null;
};

export type GetComposeDiffDto = {
    current: string | null;
    new: string | null;
};

export type GetConfigDiffDto = {
    current: string | null;
    new: string | null;
};

export type SearchAppsDto = {
    data: Array<{
        available: boolean;
        categories: Array<'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities'>;
        created_at: number;
        deprecated: boolean;
        id: string;
        name: string;
        short_desc: string;
        supported_architectures: Array<'amd64' | 'arm64'>;
        urn: string;
    }>;
    total: number;
    nextCursor?: string | null;
};

export type PullDto = {
    success: boolean;
};

export type CreateAppStoreBodyDto = {
    name: string;
    url: string;
};

export type AppStoreDto = {
    enabled: boolean;
    name: string;
    slug: string;
    url: string;
};

export type AllAppStoresDto = {
    appStores: Array<{
        enabled: boolean;
        name: string;
        slug: string;
        url: string;
    }>;
};

export type UpdateAppStoreBodyDto = {
    enabled: boolean;
    name: string;
};

export type UpdateAppStoreDto = {
    success: boolean;
};

export type AppFormBody = {
    domain?: string;
    enableAuth?: boolean;
    exposed?: boolean;
    exposedLocal?: boolean;
    isVisibleOnGuestDashboard?: boolean;
    localSubdomain?: string;
    maxBackups?: number;
    openPort?: boolean;
    port?: number;
    skipEnv?: boolean;
    skipPull?: boolean;
    skipRun?: boolean;
};

export type LifecycleRequestDto = {
    /**
     * a UUID
     */
    requestId: string | '00000000-0000-0000-0000-000000000000' | 'ffffffff-ffff-ffff-ffff-ffffffffffff';
};

export type UninstallAppBody = {
    removeBackups: boolean;
};

export type UpdateAppBody = {
    performBackup: boolean;
};

export type BackupRequestDto = {
    /**
     * a UUID
     */
    requestId: string | '00000000-0000-0000-0000-000000000000' | 'ffffffff-ffff-ffff-ffff-ffffffffffff';
};

export type RestoreAppBackupDto = {
    filename: string;
};

export type GetAppBackupsDto = {
    currentPage: number;
    data: Array<{
        date: number;
        id: string;
        size: number;
    }>;
    lastPage: number;
    total: number;
};

export type DeleteAppBackupBodyDto = {
    filename: string;
};

export type LinksDto = {
    links: Array<{
        description: string | null;
        iconUrl: string | '' | null;
        id: number;
        isVisibleOnGuestDashboard: boolean;
        title: string;
        url: string;
        userId: number;
    }>;
};

export type LinkBodyDto = {
    title: string;
    url: string;
    description?: string;
    iconUrl?: string | '';
    isVisibleOnGuestDashboard?: boolean;
};

export type EditLinkBodyDto = {
    title: string;
    url: string;
    description?: string;
    iconUrl?: string | '';
    isVisibleOnGuestDashboard?: boolean;
};

export type GetUserConfigDto = {
    appEnv: string | null;
    dockerCompose: string | null;
    isEnabled: boolean;
};

export type UpdateUserConfigDto = {
    appEnv: string;
    dockerCompose: string;
};

export type CreateCustomAppDto = {
    config: {
        schemaVersion: 2;
        services: Array<{
            image: string;
            name: string;
            addPorts?: Array<{
                containerPort: string | number;
                hostPort: string | number;
                interface?: string;
                tcp?: boolean;
                udp?: boolean;
            }>;
            addToMainNetwork?: boolean;
            capAdd?: Array<string>;
            capDrop?: Array<string>;
            command?: string | Array<string>;
            dependsOn?: {
                [key: string]: {
                    condition: 'service_completed_successfully' | 'service_healthy' | 'service_started';
                };
            } | Array<string>;
            deploy?: {
                resources: {
                    limits?: {
                        cpus?: string;
                        memory?: string;
                        pids?: number;
                    };
                    reservations?: {
                        devices: Array<{
                            capabilities: Array<string>;
                            count?: number | 'all';
                            deviceIds?: Array<string>;
                            driver?: string;
                        }>;
                        cpus?: string;
                        memory?: string;
                    };
                };
            };
            devices?: Array<string>;
            dns?: string | Array<string>;
            entrypoint?: string | Array<string>;
            environment?: Array<{
                key: string;
                value: number | string | boolean;
            }>;
            extraHosts?: Array<string>;
            extraLabels?: {
                [key: string]: string | boolean;
            };
            healthCheck?: {
                test: string;
                interval?: string;
                retries?: number;
                startInterval?: string;
                startPeriod?: string;
                timeout?: string;
            };
            hostname?: string;
            internalPort?: string | number;
            isMain?: boolean;
            logging?: {
                driver: string;
                options?: {
                    [key: string]: string;
                };
            };
            networkMode?: string;
            pid?: string;
            privileged?: boolean;
            readOnly?: boolean;
            securityOpt?: Array<string>;
            shmSize?: string;
            stdinOpen?: boolean;
            stopGracePeriod?: string;
            stopSignal?: string;
            sysctls?: {
                [key: string]: number;
            };
            tty?: boolean;
            ulimits?: {
                core?: number | {
                    hard: number;
                    soft: number;
                };
                memlock?: number | {
                    hard: number;
                    soft: number;
                };
                nofile?: number | {
                    hard: number;
                    soft: number;
                };
                nproc?: number | {
                    hard: number;
                    soft: number;
                };
            };
            user?: string;
            volumes?: Array<{
                containerPath: string;
                hostPath: string;
                bind?: {
                    propagation: 'private' | 'rprivate' | 'rshared' | 'rslave' | 'shared' | 'slave';
                };
                private?: boolean;
                readOnly?: boolean;
                shared?: boolean;
            }>;
            workingDir?: string;
        }>;
        overrides?: Array<{
            services: Array<{
                addPorts?: Array<{
                    containerPort: string | number;
                    hostPort: string | number;
                    interface?: string;
                    tcp?: boolean;
                    udp?: boolean;
                }>;
                addToMainNetwork?: boolean;
                capAdd?: Array<string>;
                capDrop?: Array<string>;
                command?: string | Array<string>;
                dependsOn?: {
                    [key: string]: {
                        condition: 'service_completed_successfully' | 'service_healthy' | 'service_started';
                    };
                } | Array<string>;
                deploy?: {
                    resources: {
                        limits?: {
                            cpus?: string;
                            memory?: string;
                            pids?: number;
                        };
                        reservations?: {
                            devices: Array<{
                                capabilities: Array<string>;
                                count?: number | 'all';
                                deviceIds?: Array<string>;
                                driver?: string;
                            }>;
                            cpus?: string;
                            memory?: string;
                        };
                    };
                };
                devices?: Array<string>;
                dns?: string | Array<string>;
                entrypoint?: string | Array<string>;
                environment?: Array<{
                    key: string;
                    value: number | string | boolean;
                }>;
                extraHosts?: Array<string>;
                extraLabels?: {
                    [key: string]: string | boolean;
                };
                healthCheck?: {
                    test: string;
                    interval?: string;
                    retries?: number;
                    startInterval?: string;
                    startPeriod?: string;
                    timeout?: string;
                };
                hostname?: string;
                image?: string;
                internalPort?: string | number;
                isMain?: boolean;
                logging?: {
                    driver: string;
                    options?: {
                        [key: string]: string;
                    };
                };
                name?: string;
                networkMode?: string;
                pid?: string;
                privileged?: boolean;
                readOnly?: boolean;
                securityOpt?: Array<string>;
                shmSize?: string;
                stdinOpen?: boolean;
                stopGracePeriod?: string;
                stopSignal?: string;
                sysctls?: {
                    [key: string]: number;
                };
                tty?: boolean;
                ulimits?: {
                    core?: number | {
                        hard: number;
                        soft: number;
                    };
                    memlock?: number | {
                        hard: number;
                        soft: number;
                    };
                    nofile?: number | {
                        hard: number;
                        soft: number;
                    };
                    nproc?: number | {
                        hard: number;
                        soft: number;
                    };
                };
                user?: string;
                volumes?: Array<{
                    containerPath: string;
                    hostPath: string;
                    bind?: {
                        propagation: 'private' | 'rprivate' | 'rshared' | 'rslave' | 'shared' | 'slave';
                    };
                    private?: boolean;
                    readOnly?: boolean;
                    shared?: boolean;
                }>;
                workingDir?: string;
            }>;
            architecture?: 'amd64' | 'arm64';
        }>;
    };
    name: string;
};

export type CreateCustomAppResponseDto = {
    appName: string;
    appUrn: string;
    storeId: string;
};

export type UpdateCustomAppDto = {
    config: {
        schemaVersion: 2;
        services: Array<{
            image: string;
            name: string;
            addPorts?: Array<{
                containerPort: string | number;
                hostPort: string | number;
                interface?: string;
                tcp?: boolean;
                udp?: boolean;
            }>;
            addToMainNetwork?: boolean;
            capAdd?: Array<string>;
            capDrop?: Array<string>;
            command?: string | Array<string>;
            dependsOn?: {
                [key: string]: {
                    condition: 'service_completed_successfully' | 'service_healthy' | 'service_started';
                };
            } | Array<string>;
            deploy?: {
                resources: {
                    limits?: {
                        cpus?: string;
                        memory?: string;
                        pids?: number;
                    };
                    reservations?: {
                        devices: Array<{
                            capabilities: Array<string>;
                            count?: number | 'all';
                            deviceIds?: Array<string>;
                            driver?: string;
                        }>;
                        cpus?: string;
                        memory?: string;
                    };
                };
            };
            devices?: Array<string>;
            dns?: string | Array<string>;
            entrypoint?: string | Array<string>;
            environment?: Array<{
                key: string;
                value: number | string | boolean;
            }>;
            extraHosts?: Array<string>;
            extraLabels?: {
                [key: string]: string | boolean;
            };
            healthCheck?: {
                test: string;
                interval?: string;
                retries?: number;
                startInterval?: string;
                startPeriod?: string;
                timeout?: string;
            };
            hostname?: string;
            internalPort?: string | number;
            isMain?: boolean;
            logging?: {
                driver: string;
                options?: {
                    [key: string]: string;
                };
            };
            networkMode?: string;
            pid?: string;
            privileged?: boolean;
            readOnly?: boolean;
            securityOpt?: Array<string>;
            shmSize?: string;
            stdinOpen?: boolean;
            stopGracePeriod?: string;
            stopSignal?: string;
            sysctls?: {
                [key: string]: number;
            };
            tty?: boolean;
            ulimits?: {
                core?: number | {
                    hard: number;
                    soft: number;
                };
                memlock?: number | {
                    hard: number;
                    soft: number;
                };
                nofile?: number | {
                    hard: number;
                    soft: number;
                };
                nproc?: number | {
                    hard: number;
                    soft: number;
                };
            };
            user?: string;
            volumes?: Array<{
                containerPath: string;
                hostPath: string;
                bind?: {
                    propagation: 'private' | 'rprivate' | 'rshared' | 'rslave' | 'shared' | 'slave';
                };
                private?: boolean;
                readOnly?: boolean;
                shared?: boolean;
            }>;
            workingDir?: string;
        }>;
        overrides?: Array<{
            services: Array<{
                addPorts?: Array<{
                    containerPort: string | number;
                    hostPort: string | number;
                    interface?: string;
                    tcp?: boolean;
                    udp?: boolean;
                }>;
                addToMainNetwork?: boolean;
                capAdd?: Array<string>;
                capDrop?: Array<string>;
                command?: string | Array<string>;
                dependsOn?: {
                    [key: string]: {
                        condition: 'service_completed_successfully' | 'service_healthy' | 'service_started';
                    };
                } | Array<string>;
                deploy?: {
                    resources: {
                        limits?: {
                            cpus?: string;
                            memory?: string;
                            pids?: number;
                        };
                        reservations?: {
                            devices: Array<{
                                capabilities: Array<string>;
                                count?: number | 'all';
                                deviceIds?: Array<string>;
                                driver?: string;
                            }>;
                            cpus?: string;
                            memory?: string;
                        };
                    };
                };
                devices?: Array<string>;
                dns?: string | Array<string>;
                entrypoint?: string | Array<string>;
                environment?: Array<{
                    key: string;
                    value: number | string | boolean;
                }>;
                extraHosts?: Array<string>;
                extraLabels?: {
                    [key: string]: string | boolean;
                };
                healthCheck?: {
                    test: string;
                    interval?: string;
                    retries?: number;
                    startInterval?: string;
                    startPeriod?: string;
                    timeout?: string;
                };
                hostname?: string;
                image?: string;
                internalPort?: string | number;
                isMain?: boolean;
                logging?: {
                    driver: string;
                    options?: {
                        [key: string]: string;
                    };
                };
                name?: string;
                networkMode?: string;
                pid?: string;
                privileged?: boolean;
                readOnly?: boolean;
                securityOpt?: Array<string>;
                shmSize?: string;
                stdinOpen?: boolean;
                stopGracePeriod?: string;
                stopSignal?: string;
                sysctls?: {
                    [key: string]: number;
                };
                tty?: boolean;
                ulimits?: {
                    core?: number | {
                        hard: number;
                        soft: number;
                    };
                    memlock?: number | {
                        hard: number;
                        soft: number;
                    };
                    nofile?: number | {
                        hard: number;
                        soft: number;
                    };
                    nproc?: number | {
                        hard: number;
                        soft: number;
                    };
                };
                user?: string;
                volumes?: Array<{
                    containerPath: string;
                    hostPath: string;
                    bind?: {
                        propagation: 'private' | 'rprivate' | 'rshared' | 'rslave' | 'shared' | 'slave';
                    };
                    private?: boolean;
                    readOnly?: boolean;
                    shared?: boolean;
                }>;
                workingDir?: string;
            }>;
            architecture?: 'amd64' | 'arm64';
        }>;
    };
};

export type UpdateAppMetadataDto = {
    data: string;
};

export type UserContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-context';
};

export type UserContextResponses = {
    default: UserContextDto;
};

export type UserContextResponse = UserContextResponses[keyof UserContextResponses];

export type AppContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-context';
};

export type AppContextResponses = {
    default: AppContextDto;
};

export type AppContextResponse = AppContextResponses[keyof AppContextResponses];

export type UpdateUserSettingsData = {
    body: UserSettingsBody;
    path?: never;
    query?: never;
    url: '/api/user-settings';
};

export type UpdateUserSettingsResponses = {
    200: unknown;
};

export type AcknowledgeWelcomeData = {
    body: AcknowledgeWelcomeBody;
    path?: never;
    query?: never;
    url: '/api/acknowledge-welcome';
};

export type AcknowledgeWelcomeResponses = {
    200: unknown;
};

export type SystemLoadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/load';
};

export type SystemLoadResponses = {
    default: LoadDto;
};

export type SystemLoadResponse = SystemLoadResponses[keyof SystemLoadResponses];

export type DownloadLocalCertificateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/certificate';
};

export type DownloadLocalCertificateResponses = {
    200: unknown;
};

export type GetTranslationData = {
    body?: never;
    path: {
        ns: string;
        lng: string;
    };
    query?: never;
    url: '/api/i18n/locales/{ns}/{lng}.json';
};

export type GetTranslationResponses = {
    200: unknown;
};

export type LoginData = {
    body: LoginBody;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    default: LoginDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type VerifyTotpData = {
    body: VerifyTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/verify-totp';
};

export type VerifyTotpResponses = {
    default: LoginDto;
};

export type VerifyTotpResponse = VerifyTotpResponses[keyof VerifyTotpResponses];

export type RegisterData = {
    body: RegisterBody;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    default: RegisterDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    201: unknown;
};

export type ChangeUsernameData = {
    body: ChangeUsernameBody;
    path?: never;
    query?: never;
    url: '/api/auth/username';
};

export type ChangeUsernameResponses = {
    200: unknown;
};

export type ChangePasswordData = {
    body: ChangePasswordBody;
    path?: never;
    query?: never;
    url: '/api/auth/password';
};

export type ChangePasswordResponses = {
    200: unknown;
};

export type GetTotpUriData = {
    body: GetTotpUriBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/get-uri';
};

export type GetTotpUriResponses = {
    default: GetTotpUriDto;
};

export type GetTotpUriResponse = GetTotpUriResponses[keyof GetTotpUriResponses];

export type SetupTotpData = {
    body: SetupTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/setup';
};

export type SetupTotpResponses = {
    200: unknown;
};

export type DisableTotpData = {
    body: DisableTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/disable';
};

export type DisableTotpResponses = {
    200: unknown;
};

export type CancelResetPasswordData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type CancelResetPasswordResponses = {
    200: unknown;
};

export type CheckResetPasswordRequestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type CheckResetPasswordRequestResponses = {
    default: CheckResetPasswordRequestDto;
};

export type CheckResetPasswordRequestResponse = CheckResetPasswordRequestResponses[keyof CheckResetPasswordRequestResponses];

export type ResetPasswordData = {
    body: ResetPasswordBody;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type ResetPasswordResponses = {
    default: ResetPasswordDto;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type TraefikData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/traefik';
};

export type TraefikResponses = {
    200: unknown;
};

export type GetInstalledAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/installed';
};

export type GetInstalledAppsResponses = {
    default: MyAppsDto;
};

export type GetInstalledAppsResponse = GetInstalledAppsResponses[keyof GetInstalledAppsResponses];

export type GetGuestAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/guest';
};

export type GetGuestAppsResponses = {
    default: GuestAppsDto;
};

export type GetGuestAppsResponse = GetGuestAppsResponses[keyof GetGuestAppsResponses];

export type GetRandomPortData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/random-port';
};

export type GetRandomPortResponses = {
    default: GetRandomPortDto;
};

export type GetRandomPortResponse = GetRandomPortResponses[keyof GetRandomPortResponses];

export type GetAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}';
};

export type GetAppResponses = {
    default: GetAppDto;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type GetAppComposeDiffData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/compose-diff';
};

export type GetAppComposeDiffResponses = {
    default: GetComposeDiffDto;
};

export type GetAppComposeDiffResponse = GetAppComposeDiffResponses[keyof GetAppComposeDiffResponses];

export type GetAppConfigDiffData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/config-diff';
};

export type GetAppConfigDiffResponses = {
    default: GetConfigDiffDto;
};

export type GetAppConfigDiffResponse = GetAppConfigDiffResponses[keyof GetAppConfigDiffResponses];

export type IgnoreAppVersionData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/ignore-version';
};

export type IgnoreAppVersionResponses = {
    200: unknown;
};

export type UnignoreAppVersionData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/unignore-version';
};

export type UnignoreAppVersionResponses = {
    200: unknown;
};

export type SearchAppsData = {
    body?: never;
    path?: never;
    query?: {
        category?: 'ai' | 'automation' | 'books' | 'data' | 'development' | 'featured' | 'finance' | 'gaming' | 'media' | 'music' | 'network' | 'photography' | 'security' | 'social' | 'utilities';
        cursor?: string;
        pageSize?: number | string;
        search?: string;
        storeId?: string;
    };
    url: '/api/marketplace/apps/search';
};

export type SearchAppsResponses = {
    default: SearchAppsDto;
};

export type SearchAppsResponse = SearchAppsResponses[keyof SearchAppsResponses];

export type GetImageData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/marketplace/apps/{urn}/image';
};

export type GetImageResponses = {
    200: unknown;
};

export type PullAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/pull';
};

export type PullAppStoresResponses = {
    default: PullDto;
};

export type PullAppStoresResponse = PullAppStoresResponses[keyof PullAppStoresResponses];

export type CreateAppStoreData = {
    body: CreateAppStoreBodyDto;
    path?: never;
    query?: never;
    url: '/api/marketplace/create';
};

export type CreateAppStoreResponses = {
    default: AppStoreDto;
};

export type CreateAppStoreResponse = CreateAppStoreResponses[keyof CreateAppStoreResponses];

export type GetAllAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/all';
};

export type GetAllAppStoresResponses = {
    default: AllAppStoresDto;
};

export type GetAllAppStoresResponse = GetAllAppStoresResponses[keyof GetAllAppStoresResponses];

export type GetEnabledAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/enabled';
};

export type GetEnabledAppStoresResponses = {
    default: AllAppStoresDto;
};

export type GetEnabledAppStoresResponse = GetEnabledAppStoresResponses[keyof GetEnabledAppStoresResponses];

export type DeleteAppStoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/marketplace/{id}';
};

export type DeleteAppStoreResponses = {
    200: unknown;
};

export type UpdateAppStoreData = {
    body: UpdateAppStoreBodyDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/marketplace/{id}';
};

export type UpdateAppStoreResponses = {
    default: UpdateAppStoreDto;
};

export type UpdateAppStoreResponse = UpdateAppStoreResponses[keyof UpdateAppStoreResponses];

export type InstallAppData = {
    body: AppFormBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/install';
};

export type InstallAppResponses = {
    default: LifecycleRequestDto;
};

export type InstallAppResponse = InstallAppResponses[keyof InstallAppResponses];

export type StartAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/start';
};

export type StartAppResponses = {
    default: LifecycleRequestDto;
};

export type StartAppResponse = StartAppResponses[keyof StartAppResponses];

export type StopAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/stop';
};

export type StopAppResponses = {
    default: LifecycleRequestDto;
};

export type StopAppResponse = StopAppResponses[keyof StopAppResponses];

export type RestartAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/restart';
};

export type RestartAppResponses = {
    default: LifecycleRequestDto;
};

export type RestartAppResponse = RestartAppResponses[keyof RestartAppResponses];

export type UninstallAppData = {
    body: UninstallAppBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/uninstall';
};

export type UninstallAppResponses = {
    default: LifecycleRequestDto;
};

export type UninstallAppResponse = UninstallAppResponses[keyof UninstallAppResponses];

export type ResetAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/reset';
};

export type ResetAppResponses = {
    default: LifecycleRequestDto;
};

export type ResetAppResponse = ResetAppResponses[keyof ResetAppResponses];

export type UpdateAppData = {
    body: UpdateAppBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/update';
};

export type UpdateAppResponses = {
    default: LifecycleRequestDto;
};

export type UpdateAppResponse = UpdateAppResponses[keyof UpdateAppResponses];

export type UpdateAppConfigData = {
    body: AppFormBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/update-config';
};

export type UpdateAppConfigResponses = {
    default: LifecycleRequestDto;
};

export type UpdateAppConfigResponse = UpdateAppConfigResponses[keyof UpdateAppConfigResponses];

export type UpdateAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/update-all';
};

export type UpdateAllAppsResponses = {
    200: unknown;
};

export type StartAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/start-all';
};

export type StartAllAppsResponses = {
    201: unknown;
};

export type StopAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/stop-all';
};

export type StopAllAppsResponses = {
    201: unknown;
};

export type RestartAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/restart-all';
};

export type RestartAllAppsResponses = {
    201: unknown;
};

export type BackupAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/backup';
};

export type BackupAppResponses = {
    default: BackupRequestDto;
};

export type BackupAppResponse = BackupAppResponses[keyof BackupAppResponses];

export type RestoreAppBackupData = {
    body: RestoreAppBackupDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/restore';
};

export type RestoreAppBackupResponses = {
    default: BackupRequestDto;
};

export type RestoreAppBackupResponse = RestoreAppBackupResponses[keyof RestoreAppBackupResponses];

export type DeleteAppBackupData = {
    body: DeleteAppBackupBodyDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}';
};

export type DeleteAppBackupResponses = {
    200: unknown;
};

export type GetAppBackupsData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/api/backups/{urn}';
};

export type GetAppBackupsResponses = {
    default: GetAppBackupsDto;
};

export type GetAppBackupsResponse = GetAppBackupsResponses[keyof GetAppBackupsResponses];

export type DownloadBackupData = {
    body?: never;
    path: {
        urn: string;
        filename: string;
    };
    query?: never;
    url: '/api/backups/{urn}/{filename}/download';
};

export type DownloadBackupResponses = {
    /**
     * Backup file download
     */
    200: unknown;
};

export type UploadBackupData = {
    body: {
        file?: Blob | File;
    };
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/upload';
};

export type UploadBackupResponses = {
    /**
     * Backup uploaded successfully
     */
    201: unknown;
};

export type AppEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/app';
};

export type AppEventsResponses = {
    200: unknown;
};

export type AppLogsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/app-logs';
};

export type AppLogsEventsResponses = {
    200: unknown;
};

export type RuntipiLogsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/runtipi-logs';
};

export type RuntipiLogsEventsResponses = {
    200: unknown;
};

export type GetGuestLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/links/guest';
};

export type GetGuestLinksResponses = {
    default: LinksDto;
};

export type GetGuestLinksResponse = GetGuestLinksResponses[keyof GetGuestLinksResponses];

export type GetLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/links';
};

export type GetLinksResponses = {
    default: LinksDto;
};

export type GetLinksResponse = GetLinksResponses[keyof GetLinksResponses];

export type CreateLinkData = {
    body: LinkBodyDto;
    path?: never;
    query?: never;
    url: '/api/links';
};

export type CreateLinkResponses = {
    201: unknown;
};

export type DeleteLinkData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/links/{id}';
};

export type DeleteLinkResponses = {
    200: unknown;
};

export type EditLinkData = {
    body: EditLinkBodyDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/links/{id}';
};

export type EditLinkResponses = {
    200: unknown;
};

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type CheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
    };
};

export type CheckError = CheckErrors[keyof CheckErrors];

export type CheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
    };
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type GetUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}';
};

export type GetUserConfigResponses = {
    default: GetUserConfigDto;
};

export type GetUserConfigResponse = GetUserConfigResponses[keyof GetUserConfigResponses];

export type UpdateUserConfigData = {
    body: UpdateUserConfigDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}';
};

export type UpdateUserConfigResponses = {
    200: unknown;
};

export type EnableUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}/enable';
};

export type EnableUserConfigResponses = {
    201: unknown;
};

export type DisableUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}/disable';
};

export type DisableUserConfigResponses = {
    201: unknown;
};

export type CreateCustomAppData = {
    body: CreateCustomAppDto;
    path?: never;
    query?: never;
    url: '/api/custom-apps';
};

export type CreateCustomAppResponses = {
    default: CreateCustomAppResponseDto;
};

export type CreateCustomAppResponse = CreateCustomAppResponses[keyof CreateCustomAppResponses];

export type UpdateCustomAppData = {
    body: UpdateCustomAppDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}';
};

export type UpdateCustomAppResponses = {
    default: unknown;
};

export type UploadAppImageData = {
    body: {
        image?: Blob | File;
    };
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}/image';
};

export type UploadAppImageResponses = {
    /**
     * Logo uploaded successfully
     */
    200: unknown;
};

export type UpdateAppMetadataData = {
    body: UpdateAppMetadataDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}/metadata';
};

export type UpdateAppMetadataResponses = {
    default: unknown;
};

export type SeedDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/seed';
};

export type SeedDatabaseResponses = {
    201: unknown;
};

export type SetAllAppUpdateAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/set-all-app-update-available';
};

export type SetAllAppUpdateAvailableResponses = {
    201: unknown;
};

export type SetAllAppSubnetToNullData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/set-all-subnets-to-null';
};

export type SetAllAppSubnetToNullResponses = {
    201: unknown;
};

export type StartAllApps2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/start-all-apps';
};

export type StartAllApps2Responses = {
    201: unknown;
};

export type BackupAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/backup-all-apps';
};

export type BackupAllAppsResponses = {
    201: unknown;
};

export type IncrementAllAppVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/increment-all-app-versions';
};

export type IncrementAllAppVersionsResponses = {
    201: unknown;
};

export type UninstallAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/uninstall-all-apps';
};

export type UninstallAllAppsResponses = {
    201: unknown;
};
