ARG NODE_VERSION="18.12.1"
ARG ALPINE_VERSION="3.16"

FROM node:${NODE_VERSION}-buster-slim 
WORKDIR /

RUN apt update
RUN apt install -y openssl

RUN npm install node-gyp -g

WORKDIR /dashboard
COPY ./packages/dashboard/package*.json /dashboard/
COPY ./packages/dashboard/prisma/schema.prisma /dashboard/prisma/
RUN npm install

COPY ./packages/dashboard /dashboard

CMD ["npm", "run", "dev"]
