ARG NODE_VERSION="18.12.1"
ARG ALPINE_VERSION="3.16"

FROM node:${NODE_VERSION}-buster-slim 

RUN apt update
RUN apt install -y openssl

RUN npm install pnpm -g
RUN npm install node-gyp -g

WORKDIR /app

COPY ./pnpm-lock.yaml ./
RUN pnpm fetch

COPY ./package*.json ./
COPY ./prisma/schema.prisma ./prisma/

RUN pnpm install -r --prefer-offline 

# COPY ./src ./src
COPY ./esbuild.js ./esbuild.js
COPY ./tsconfig.json ./tsconfig.json
COPY ./next.config.mjs ./next.config.mjs
COPY ./public ./public

CMD ["npm", "run", "dev"]
