version: "3.7"

services:
  # unbound:
  #   image: "klutchell/unbound"
  #   container_name: unbound
  #   restart: unless-stopped
  #   volumes:
  #     - "${APP_DATA_DIR}/data/unbound:/etc/unbound"
  #   networks:
  #     tipi_main_network:
  #       ipv4_address: 10.21.21.200

  pihole:
    # depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:2022.07.1
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      # - 10.21.21.200 # Points to unbound
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${APP_PASSWORD}
      # PIHOLE_DNS_: 10.21.21.200 # Points to unbound
      FTLCONF_REPLY_ADDR4: 10.21.21.201
    cap_add:
      - NET_ADMIN
    networks:
      tipi_main_network:
        ipv4_address: 10.21.21.201
