name: Tipi CI
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - name: Run biome tests
        run: bun run lint:ci

      - name: Run tests
        run: bun run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - name: Build client
        run: bun run bundle

      - name: Run tsc
        run: bun run tsc
