name: Publish translations

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move translations
        run: |
          mkdir -p dist/i18n/translation
          mv packages/backend/src/modules/i18n/translations/* dist/i18n

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: translations
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: translations

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_PAGES_API_TOKEN }}
        run: |
          wrangler pages delpoy dist --project-name runtipi-translations --branch main
